### ISSUE TITLE
Argument order?

### ISSUE THREAD

**Issue by KeithGillette** [dsherret/barrel-maintainer#3]
The `readme.md` indicates that the argument order for `barrel-maintainer` is `barrel-maintainer [options] [path]`. However, I have found that both at the command line and when invoked from a `package.json` npm script, `[path]` is ignored in favor of the working directory unless specified before `[options]`

**Comment by dsherret** [comment]
Hi @KeithGillette, thanks for reporting this! I got confused by the second example in minimist [documentation](https://github.com/substack/minimist#example) because it actually doesn't work that way by default which I assumed.

Anyway, this issue is fixed in 1.2.11.
