### ISSUE TITLE
When starting the tool it crashes with "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by ChristianIvicevic** [dsherret/barrel-maintainer#7]
Basically what the title says, when invoking the tool (either after installing it globally or in the project itself) it crashes with the error message `env: node\r: No such file or directory`.

Any idea how I can help to find the cause?

**Comment by ChristianIvicevic** [comment]
Oh I found the cause already - the `cli.js` has CRLF line endings causing macOS to fail. I propose that you fix the corresponding line endings to LF. A manual change of line endings in the `dist/cli.js` will help temporarily.

**Comment by dsherret** [comment]
@ChristianIvicevic thanks for figuring out the fix! I published a new version.
